[[redirects]]
from = "/*"
to = "/"
status = 404
force = false

[[redirects]]
from = "/404"
to = "/"
status = 302
force = true

[[redirects]]
from = "/test4"
to = "/"
status = 404


[[redirects]]
from = "/test2"
to = "/"
status = 200

